-- ============================================================
-- BW 수익성분석 데이터 테이블
-- 핵심 실적 데이터 (약 58만 행)
-- ============================================================

CREATE TABLE IF NOT EXISTS `bw_profitability_data` (
  `SEQ`            bigint(20)    NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `CALYEAR`        varchar(10)   DEFAULT NULL COMMENT '달력연도',
  `CALMONTH`       varchar(10)   DEFAULT NULL COMMENT '달력연도/월',
  `CALDAY`         varchar(10)   DEFAULT NULL COMMENT '달력일',
  `CO_AREA`        varchar(10)   DEFAULT NULL COMMENT '관리회계 영역',
  `CO_AREA_NM`     varchar(100)  DEFAULT NULL COMMENT '관리회계 영역명',
  `PROFIT_CTR`     varchar(20)   DEFAULT NULL COMMENT '손익 센터',
  `PROFIT_CTR_NM`  varchar(100)  DEFAULT NULL COMMENT '손익센터명',
  `DIVISION`       varchar(5)    DEFAULT NULL COMMENT '제품군',
  `DIVISION_NM`    varchar(100)  DEFAULT NULL COMMENT '제품군명',
  `PLANT`          varchar(10)   DEFAULT NULL COMMENT '플랜트',
  `PLANT_NM`       varchar(100)  DEFAULT NULL COMMENT '플랜트명',
  `DISTR_CHAN`     varchar(5)    DEFAULT NULL COMMENT '유통 경로',
  `DISTR_CHAN_NM`  varchar(100)  DEFAULT NULL COMMENT '유통경로명',
  `ZDISTCHAN`      varchar(5)    DEFAULT NULL COMMENT '내수/수출구분자(사업장)',
  `ZORG_TEAM`      varchar(10)   DEFAULT NULL COMMENT '영업팀(사업장그룹)',
  `SALES_OFF`      varchar(10)   DEFAULT NULL COMMENT '사업장',
  `SALES_OFF_NM`   varchar(100)  DEFAULT NULL COMMENT '사업장명',
  `MATL_TYPE`      varchar(10)   DEFAULT NULL COMMENT '자재유형',
  `MATL_TYPE_NM`   varchar(100)  DEFAULT NULL COMMENT '자재유형명',
  `MATL_GROUP`     varchar(10)   DEFAULT NULL COMMENT '자재 그룹',
  `MATL_GROUP_NM`  varchar(100)  DEFAULT NULL COMMENT '자재 그룹명',
  `PRODH1`         varchar(10)   DEFAULT NULL COMMENT '제품계층 구조레벨 1',
  `PRODH1_NM`      varchar(100)  DEFAULT NULL COMMENT '제품군 (제품군 대)',
  `PRODH2`         varchar(10)   DEFAULT NULL COMMENT '제품 계층구조레벨 2',
  `PRODH2_NM`      varchar(100)  DEFAULT NULL COMMENT '지종 (제품군 중)',
  `PRODH3`         varchar(15)   DEFAULT NULL COMMENT '제품 계층구조레벨 3',
  `PRODH3_NM`      varchar(100)  DEFAULT NULL COMMENT '품목군 (제품군 소)',
  `PRODH4`         varchar(20)   DEFAULT NULL COMMENT '제품 계층구조레벨 4',
  `PRODH4_NM`      varchar(100)  DEFAULT NULL COMMENT '스펙, 사이즈, 크기, 지폭',
  `ZJPCODE`        varchar(10)   DEFAULT NULL COMMENT '지종/제품구분',
  `ZJPCODE_NM`     varchar(100)  DEFAULT NULL COMMENT '지종/제품구분명',
  `ZBRAND`         varchar(10)   DEFAULT NULL COMMENT '브랜드 1',
  `ZBRAND_NM`      varchar(100)  DEFAULT NULL COMMENT '브랜드 1 명',
  `ZSBRAND`        varchar(10)   DEFAULT NULL COMMENT '브랜드 2',
  `ZSBRAND_NM`     varchar(100)  DEFAULT NULL COMMENT '브랜드 2 명',
  `BILL_TYPE`      varchar(10)   DEFAULT NULL COMMENT '대금청구유형',
  `BILL_TYPE_NM`   varchar(100)  DEFAULT NULL COMMENT '대금청구유형 명',
  `INCOTERMS`      varchar(5)    DEFAULT NULL COMMENT '인도 조건',
  `INCOTERMS_NM`   varchar(100)  DEFAULT NULL COMMENT '인도 조건 명',
  `CUST_GROUP`     varchar(5)    DEFAULT NULL COMMENT '고객 그룹',
  `CUST_GROUP_NM`  varchar(100)  DEFAULT NULL COMMENT '고객그룹 명',
  `CUST_GRP1`      varchar(5)    DEFAULT NULL COMMENT '고객 그룹 1',
  `CUST_GRP1_NM`   varchar(100)  DEFAULT NULL COMMENT '고객그룹1 명',
  `COUNTRY`        varchar(5)    DEFAULT NULL COMMENT '국가',
  `COUNTRY_NM`     varchar(100)  DEFAULT NULL COMMENT '국가 명',
  `ZKUNN2`         varchar(20)   DEFAULT NULL COMMENT '영업사원',
  `ZKUNN2_NM`      varchar(100)  DEFAULT NULL COMMENT '영업사원 명',
  `CUSTOMER`       varchar(20)   DEFAULT NULL COMMENT '고객',
  `CUSTOMER_NM`    varchar(100)  DEFAULT NULL COMMENT '고객 명',
  `MATERIAL`       varchar(30)   DEFAULT NULL COMMENT '자재',
  `MATERIAL_NM`    varchar(100)  DEFAULT NULL COMMENT '자재 명',
  `ZBOXUNIT`       varchar(5)    DEFAULT NULL COMMENT 'BOX단위',
  `ZBAGUNIT`       varchar(5)    DEFAULT NULL COMMENT 'BAG단위',
  `ZUNIT`          varchar(5)    DEFAULT NULL COMMENT '기준수량단위(KG/EA)',
  `CURRENCY`       varchar(5)    DEFAULT NULL COMMENT '통화',
  `ZQTY_BOX`       decimal(18,3) DEFAULT NULL COMMENT '수량(BOX)',
  `ZQTY_BAG`       bigint(20)    DEFAULT NULL COMMENT '수량(BAG)',
  `ZQTY_KE`        decimal(18,3) DEFAULT NULL COMMENT '수량(KG/EA)',
  `ZAMT001`        bigint(20)    DEFAULT NULL COMMENT '총매출',
  `ZAMT002`        bigint(20)    DEFAULT NULL COMMENT '판매장려금',
  `ZAMT003`        bigint(20)    DEFAULT NULL COMMENT '순매출',
  `ZAMT004`        bigint(20)    DEFAULT NULL COMMENT '기타매출',
  `ZAMT005`        bigint(20)    DEFAULT NULL COMMENT '매출원가(제품)',
  `ZAMT006`        bigint(20)    DEFAULT NULL COMMENT '재료비-펄프',
  `ZAMT007`        bigint(20)    DEFAULT NULL COMMENT '재료비-고지',
  `ZAMT008`        bigint(20)    DEFAULT NULL COMMENT '재료비-패드',
  `ZAMT009`        bigint(20)    DEFAULT NULL COMMENT '부재료비-약품',
  `ZAMT010`        bigint(20)    DEFAULT NULL COMMENT '부재료비-포장재',
  `ZAMT011`        bigint(20)    DEFAULT NULL COMMENT '재료비-기타',
  `ZAMT012`        bigint(20)    DEFAULT NULL COMMENT '인건비',
  `ZAMT013`        bigint(20)    DEFAULT NULL COMMENT '인건비_경비',
  `ZAMT014`        bigint(20)    DEFAULT NULL COMMENT '인건비_기타',
  `ZAMT015`        bigint(20)    DEFAULT NULL COMMENT '도급비',
  `ZAMT016`        bigint(20)    DEFAULT NULL COMMENT '에너지비',
  `ZAMT017`        bigint(20)    DEFAULT NULL COMMENT '전력비',
  `ZAMT018`        bigint(20)    DEFAULT NULL COMMENT '감가상각비',
  `ZAMT019`        bigint(20)    DEFAULT NULL COMMENT '수선/소모품비',
  `ZAMT020`        bigint(20)    DEFAULT NULL COMMENT '기타경비',
  `ZAMT021`        bigint(20)    DEFAULT NULL COMMENT '기타경비_폐기물',
  `ZAMT022`        bigint(20)    DEFAULT NULL COMMENT '기타경비_세금과공과',
  `ZAMT023`        bigint(20)    DEFAULT NULL COMMENT '기타경비_지급수수료',
  `ZAMT024`        bigint(20)    DEFAULT NULL COMMENT '외주가공비',
  `ZAMT025`        bigint(20)    DEFAULT NULL COMMENT '매출원가(상품)',
  `ZAMT026`        bigint(20)    DEFAULT NULL COMMENT '매출원가(기타)',
  `ZAMT027`        bigint(20)    DEFAULT NULL COMMENT '기타원가',
  `ZAMT028`        bigint(20)    DEFAULT NULL COMMENT '단수차이',
  `ZAMT029`        bigint(20)    DEFAULT NULL COMMENT '차이잔액',
  `ZAMT030`        bigint(20)    DEFAULT NULL COMMENT '제조파지정산',
  `ZAMT031`        bigint(20)    DEFAULT NULL COMMENT '기타매출원가+감모손+평가손',
  `ZAMT032`        bigint(20)    DEFAULT NULL COMMENT '원재료 투입차이',
  `ZAMT033`        bigint(20)    DEFAULT NULL COMMENT '기타매출원가 배부조',
  `ZAMT034`        bigint(20)    DEFAULT NULL COMMENT '매출원가 계',
  `ZAMT035`        bigint(20)    DEFAULT NULL COMMENT '매출총이익',
  `ZAMT036`        bigint(20)    DEFAULT NULL COMMENT '판매관리비',
  `ZAMT037`        bigint(20)    DEFAULT NULL COMMENT '급여(변동)',
  `ZAMT038`        bigint(20)    DEFAULT NULL COMMENT '국내운반비(변동)',
  `ZAMT039`        bigint(20)    DEFAULT NULL COMMENT '수출운반비(변동)',
  `ZAMT040`        bigint(20)    DEFAULT NULL COMMENT '지급수수료(변동)',
  `ZAMT041`        bigint(20)    DEFAULT NULL COMMENT '기타판관비(변동)',
  `ZAMT042`        bigint(20)    DEFAULT NULL COMMENT '개발비(변동)',
  `ZAMT043`        bigint(20)    DEFAULT NULL COMMENT '급여(고정)',
  `ZAMT044`        bigint(20)    DEFAULT NULL COMMENT '지급수수료(고정)',
  `ZAMT045`        bigint(20)    DEFAULT NULL COMMENT '기타판관비(고정)',
  `ZAMT046`        bigint(20)    DEFAULT NULL COMMENT '개발비(고정)',
  `ZAMT047`        bigint(20)    DEFAULT NULL COMMENT '마케팅비',
  `ZAMT048`        bigint(20)    DEFAULT NULL COMMENT '광고비',
  `ZAMT049`        bigint(20)    DEFAULT NULL COMMENT '소모품비',
  `ZAMT050`        bigint(20)    DEFAULT NULL COMMENT '지급수수료-마케팅(변동)',
  `ZAMT051`        bigint(20)    DEFAULT NULL COMMENT '지급수수료-마케팅(고정)',
  `ZAMT052`        bigint(20)    DEFAULT NULL COMMENT '마케팅비_장려금(변동)',
  `ZAMT053`        bigint(20)    DEFAULT NULL COMMENT '판촉비',
  `ZAMT054`        bigint(20)    DEFAULT NULL COMMENT '마케팅비 배부조정',
  `ZAMT055`        bigint(20)    DEFAULT NULL COMMENT '영업이익',
  `ZAMT056`        bigint(20)    DEFAULT NULL COMMENT '영업외수익',
  `ZAMT057`        bigint(20)    DEFAULT NULL COMMENT '이자수익',
  `ZAMT058`        bigint(20)    DEFAULT NULL COMMENT '외환이익',
  `ZAMT059`        bigint(20)    DEFAULT NULL COMMENT '기타영업외수익',
  `ZAMT060`        bigint(20)    DEFAULT NULL COMMENT '영업외비용',
  `ZAMT061`        bigint(20)    DEFAULT NULL COMMENT '이자비용',
  `ZAMT062`        bigint(20)    DEFAULT NULL COMMENT '외환손실',
  `ZAMT063`        bigint(20)    DEFAULT NULL COMMENT '기타영업외비용',
  `ZAMT064`        bigint(20)    DEFAULT NULL COMMENT '경상이익',
  PRIMARY KEY (`SEQ`),
  KEY `idx_calmonth`   (`CALMONTH`),
  KEY `idx_calday`     (`CALDAY`),
  KEY `idx_profit_ctr` (`PROFIT_CTR`),
  KEY `idx_division`   (`DIVISION`),
  KEY `idx_plant`      (`PLANT`),
  KEY `idx_distr_chan`  (`DISTR_CHAN`),
  KEY `idx_sales_off`  (`SALES_OFF`),
  KEY `idx_prodh1`     (`PRODH1`),
  KEY `idx_customer`   (`CUSTOMER`),
  KEY `idx_material`   (`MATERIAL`),
  KEY `idx_zjpcode`    (`ZJPCODE`),
  KEY `idx_zbrand1`    (`ZBRAND`),
  KEY `idx_zorg_team`  (`ZORG_TEAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
  ROW_FORMAT=DYNAMIC COMMENT='BW수익성분석 데이터';
